---
- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600

- name: Check if a reboot is needed.
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: os_upgrade_reboot_required_file

- name: Reboot the server (if required).
  ansible.builtin.reboot:
  when: os_upgrade_reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: true
